### ISSUE TITLE
Build issue with full paths that contain spaces

### ISSUE THREAD

**Issue by AlexNiculae** [intelxed/xed#236] opened 2020-08-19 09:11 UTC
Following the building instructions provided in README.md, but changing ./mfile.py to using the full path, would result in a failure in cases where the full path contains (escaped) spaces.

**OS Platform:** macOS version 10.15.6

**How to reproduce?**
```shell
mkdir Folder\ with\ spaces/
cd Folder\ with\ spaces/
git clone https://github.com/intelxed/xed.git xed
git clone https://github.com/intelxed/mbuild.git mbuild
```
And then type and run the full path to ./xed/mfile.py

**The error I am getting:**
```shel
[EXTF PROCESSING] /Users/aniculae/Documents/Xcode Projects/xed-test/xed/datafiles/bitalg/files.cfg
[EXTF PROCESSING] /Users/aniculae/Documents/Xcode Projects/xed-test/xed/datafiles/vbmi2/files.cfg
[EXTF PROCESSING] /Users/aniculae/Documents/Xcode Projects/xed-test/xed/datafiles/gfni-vaes-vpcl/files-sse.cfg
[EXTF PROCESSING] /Users/aniculae/Documents/Xcode Projects/xed-test/xed/datafiles/gfni-vaes-vpcl/files-avx-avx512.cfg
[EXTF PROCESSING] /Users/aniculae/Documents/Xcode Projects/xed-test/xed/datafiles/vpopcntdq-vl/files.cfg
[EXTF PROCESSING] /Users/aniculae/Documents/Xcode Projects/xed-test/xed/datafiles/tgl/files.cfg
[EXTF PROCESSING] /Users/aniculae/Documents/Xcode Projects/xed-test/xed/datafiles/vp2intersect/files.cfg
[EXTF PROCESSING] /Users/aniculae/Documents/Xcode Projects/xed-test/xed/datafiles/spr/files.cfg
[EXTF PROCESSING] /Users/aniculae/Documents/Xcode Projects/xed-test/xed/datafiles/enqcmd/files.cfg
[EXTF PROCESSING] /Users/aniculae/Documents/Xcode Projects/xed-test/xed/datafiles/tsx-ldtrk/files.cfg
[EXTF PROCESSING] /Users/aniculae/Documents/Xcode Projects/xed-test/xed/datafiles/serialize/files.cfg
[EXTF PROCESSING] /Users/aniculae/Documents/Xcode Projects/xed-test/xed/datafiles/future/files.cfg
[REUSING BUILD DEFINES HEADER FILE] 
R: 2 P: 0 C: 0 E: 0 / 26 msecs [decgen encgen]
[WRITING] obj/DEC-OUT.txt
[WRITING] obj/DEC-ERR.txt
[DEC-GEN] Return code: 2
[MBUILD WARNING] Command execution failed. Waiting for remaining jobs and exiting.
R: 1 P: 0 C: 1 E: 1 / 45 msecs [encgen]
[NAME        ] decgen
[COMMAND     ] PYTHON FN: run_decode_generator
[ARGS        ] <xed_mbuild.generator_inputs_t object at 0x1100982e8>
[ENV         ] some env
[EXIT_STATUS ] 2
[OUTPUT] 
/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/aniculae/Documents/Xcode\ Projects/xed-test/xed/pysrc/generator.py': [Errno 2] No such file or directory

[WRITING] obj/ENC-OUT.txt
[WRITING] obj/ENC-ERR.txt
[ENC-GEN] Return code: 2
[MBUILD WARNING] Command execution failed. Waiting for remaining jobs and exiting.
R: 0 P: 0 C: 2 E: 2 / 45 msecs 
[NAME        ] encgen
[COMMAND     ] PYTHON FN: run_encode_generator
[ARGS        ] <xed_mbuild.generator_inputs_t object at 0x1100982e8>
[ENV         ] some env
[EXIT_STATUS ] 2

ABORT: [DECODE/ENCODE GENERATORS] failed. dying...
```

**Comment by markcharney** [comment] 2020-08-19 15:13
Ok. I reproduced this. It took me a few tries but as  you described. thanks.

1) if works if you build  from the  xed dir with  "./mfile.py"
2) it works  if you build  from  above the  xed dir with "xed/mfile.py"
3)  it fails  if you build from above  the xed dir with the  full path with  spaces  to xed/mfile.py,  as you  indicated.

I'll  take  a deeper look now.

**Comment by markcharney** [comment] 2020-08-19 15:33
I believe that I  fixed  the reported issue in  my workspace. It required a small modification in xed and one  in mbuild. I believe  there are  a few   more fixes that I probably should   make  for other  build  args; I'll work on that next.

I am long overdue to  push  out an  update  to everything.   I  will queue  that   up.

**Comment by markcharney** [comment] 2020-11-03 15:32
this should be fixed now. re-open or create new issue if you are still experiencing issues.  thx for reporting.

**Closed by markcharney** 2020-11-03 15:32 UTC
Labels: acknowledged, bug, implemented
